apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: quarkus-getting-started
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: quarkus-getting-started
  template:
    ref: quarkus-getting-started
---
